project:
  type: website

website:
  title: "The Data Misfits"
  description: "The unofficial blog of the Advanced Data Analysis Unit. We talk about everything "
  navbar:
    background: light
    foreground: dark
    right:
      - about_us.qmd
      # - projects.qmd
      # - blog.qmd
      # - publications.qmd
      # - href: about.qmd
        # text: About
format:
  html:
    theme: 
      - quartz #journal
      - custom.scss
    css: styles.css
    toc: false



